namespace RabbitTune.AudioEngine.BassWrapper
{
    internal enum BassErrors
    {
        Unknown = -1,
        OK = 0,
        Memory = 1,
        FileOpen = 2,
        Driver = 3,
        BufferLost = 4,
        Handle = 5,
        SampleFormat = 6,
        Position = 7,
        Init = 8,
        Start = 9,
        SSL = 10,
        NoCD = 12,
        CDTrack = 13,
        AlreadyInitialized = 14,
        NotPaused = 16,
        NotAudioTrack = 17,
        NoChannel = 18,
        IllegalType = 19,
        Parameter = 20,
        No3D = 21,
        EAXNotSupported = 22,
        Device = 23,
        NotPlaying = 24,
        InvalidSampleRate = 25,
        NotFile = 27,
        NoHW = 29,
        Empty = 31,
        NoInternet = 32,
        Create = 33,
        NoFX = 34,
        Playing = 35,
        NotAvailable = 37,
        Decode = 38,
        DirectX = 39,
        Timeout = 40,
        FileFormat = 41,
        Speaker = 42,
        Version = 43,
        Codec = 44,
        Ended = 45,
        Busy = 46,
        Unstreamable = 47,
    }
}
